/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { applicationUserRoleConnectionsGet } from "../funcs/applicationUserRoleConnectionsGet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ApplicationUserRoleConnections extends ClientSDK {
  async get(
    request: operations.GetApplicationUserRoleConnectionRequest,
    options?: RequestOptions,
  ): Promise<components.ApplicationUserRoleConnectionResponse> {
    return unwrapAsync(applicationUserRoleConnectionsGet(
      this,
      request,
      options,
    ));
  }
}
