/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Rules } from "./rules.js";

export class AutoModeration extends ClientSDK {
  private _rules?: Rules;
  get rules(): Rules {
    return (this._rules ??= new Rules(this._options));
  }
}
