/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { channelsThreadMembersJoin } from "../funcs/channelsThreadMembersJoin.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ChannelsThreadMembers extends ClientSDK {
  async join(
    request: operations.JoinThreadRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(channelsThreadMembersJoin(
      this,
      request,
      options,
    ));
  }
}
