/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { channelPermissionsDeleteOverwrite } from "../funcs/channelPermissionsDeleteOverwrite.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ChannelPermissions extends ClientSDK {
  async deleteOverwrite(
    request: operations.DeleteChannelPermissionOverwriteRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(channelPermissionsDeleteOverwrite(
      this,
      request,
      options,
    ));
  }
}
