/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { applicationsEmojisCreate } from "../funcs/applicationsEmojisCreate.js";
import { applicationsEmojisDelete } from "../funcs/applicationsEmojisDelete.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Emojis extends ClientSDK {
  async delete(
    request: operations.DeleteApplicationEmojiRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(applicationsEmojisDelete(
      this,
      request,
      options,
    ));
  }

  async create(
    request: operations.CreateApplicationEmojiRequest,
    options?: RequestOptions,
  ): Promise<components.EmojiResponse> {
    return unwrapAsync(applicationsEmojisCreate(
      this,
      request,
      options,
    ));
  }
}
