/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { guildVoiceRegionsList } from "../funcs/guildVoiceRegionsList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class GuildVoiceRegions extends ClientSDK {
  async list(
    request: operations.ListGuildVoiceRegionsRequest,
    options?: RequestOptions,
  ): Promise<Array<components.VoiceRegionResponse>> {
    return unwrapAsync(guildVoiceRegionsList(
      this,
      request,
      options,
    ));
  }
}
