/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { guildStickersList } from "../funcs/guildStickersList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class GuildStickers extends ClientSDK {
  async list(
    request: operations.ListGuildStickersRequest,
    options?: RequestOptions,
  ): Promise<Array<components.GuildStickerResponse>> {
    return unwrapAsync(guildStickersList(
      this,
      request,
      options,
    ));
  }
}
