/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Answers } from "./answers.js";
import { Applications } from "./applications.js";
import { ApplicationsCommands } from "./applicationscommands.js";
import { ApplicationUserRoleConnection } from "./applicationuserroleconnection.js";
import { ApplicationUserRoleConnections } from "./applicationuserroleconnections.js";
import { AutoModerationRules } from "./automoderationrules.js";
import { ChannelPermissions } from "./channelpermissions.js";
import { Channels } from "./channels.js";
import { ChannelsRecipients } from "./channelsrecipients.js";
import { ChannelsThreadMembers } from "./channelsthreadmembers.js";
import { Gateway } from "./gateway.js";
import { GuildApplicationCommands } from "./guildapplicationcommands.js";
import { GuildBans } from "./guildbans.js";
import { GuildCommands } from "./guildcommands.js";
import { GuildEmojis } from "./guildemojis.js";
import { GuildIntegrations } from "./guildintegrations.js";
import { GuildMemberRoles } from "./guildmemberroles.js";
import { GuildMembers } from "./guildmembers.js";
import { GuildOnboarding } from "./guildonboarding.js";
import { GuildRoles } from "./guildroles.js";
import { Guilds } from "./guilds.js";
import { GuildsChannels } from "./guildschannels.js";
import { GuildScheduledEvents } from "./guildscheduledevents.js";
import { GuildsMembers } from "./guildsmembers.js";
import { GuildSoundboardSounds } from "./guildsoundboardsounds.js";
import { GuildsSoundboardSounds } from "./guildssoundboardsounds.js";
import { GuildStickers } from "./guildstickers.js";
import { GuildTemplates } from "./guildtemplates.js";
import { GuildThreads } from "./guildthreads.js";
import { GuildVoiceRegions } from "./guildvoiceregions.js";
import { GuildWidgetSettings } from "./guildwidgetsettings.js";
import { Invites } from "./invites.js";
import { MessageReactions } from "./messagereactions.js";
import { Messages } from "./messages.js";
import { Oauth2 } from "./oauth2.js";
import { ScheduledEvents } from "./scheduledevents.js";
import { Soundboard } from "./soundboard.js";
import { StageInstances } from "./stageinstances.js";
import { StickerPacks } from "./stickerpacks.js";
import { Stickers } from "./stickers.js";
import { ThreadMembers } from "./threadmembers.js";
import { Threads } from "./threads.js";
import { Users } from "./users.js";
import { Voice } from "./voice.js";
import { WebhookMessages } from "./webhookmessages.js";
import { Webhooks } from "./webhooks.js";

export class Discord extends ClientSDK {
  private _oauth2?: Oauth2;
  get oauth2(): Oauth2 {
    return (this._oauth2 ??= new Oauth2(this._options));
  }

  private _users?: Users;
  get users(): Users {
    return (this._users ??= new Users(this._options));
  }

  private _applications?: Applications;
  get applications(): Applications {
    return (this._applications ??= new Applications(this._options));
  }

  private _gateway?: Gateway;
  get gateway(): Gateway {
    return (this._gateway ??= new Gateway(this._options));
  }

  private _voice?: Voice;
  get voice(): Voice {
    return (this._voice ??= new Voice(this._options));
  }

  private _soundboard?: Soundboard;
  get soundboard(): Soundboard {
    return (this._soundboard ??= new Soundboard(this._options));
  }

  private _stageInstances?: StageInstances;
  get stageInstances(): StageInstances {
    return (this._stageInstances ??= new StageInstances(this._options));
  }

  private _stickerPacks?: StickerPacks;
  get stickerPacks(): StickerPacks {
    return (this._stickerPacks ??= new StickerPacks(this._options));
  }

  private _guilds?: Guilds;
  get guilds(): Guilds {
    return (this._guilds ??= new Guilds(this._options));
  }

  private _channels?: Channels;
  get channels(): Channels {
    return (this._channels ??= new Channels(this._options));
  }

  private _threads?: Threads;
  get threads(): Threads {
    return (this._threads ??= new Threads(this._options));
  }

  private _applicationUserRoleConnections?: ApplicationUserRoleConnections;
  get applicationUserRoleConnections(): ApplicationUserRoleConnections {
    return (this._applicationUserRoleConnections ??=
      new ApplicationUserRoleConnections(this._options));
  }

  private _applicationUserRoleConnection?: ApplicationUserRoleConnection;
  get applicationUserRoleConnection(): ApplicationUserRoleConnection {
    return (this._applicationUserRoleConnection ??=
      new ApplicationUserRoleConnection(this._options));
  }

  private _guildCommands?: GuildCommands;
  get guildCommands(): GuildCommands {
    return (this._guildCommands ??= new GuildCommands(this._options));
  }

  private _guildApplicationCommands?: GuildApplicationCommands;
  get guildApplicationCommands(): GuildApplicationCommands {
    return (this._guildApplicationCommands ??= new GuildApplicationCommands(
      this._options,
    ));
  }

  private _channelsThreadMembers?: ChannelsThreadMembers;
  get channelsThreadMembers(): ChannelsThreadMembers {
    return (this._channelsThreadMembers ??= new ChannelsThreadMembers(
      this._options,
    ));
  }

  private _messages?: Messages;
  get messages(): Messages {
    return (this._messages ??= new Messages(this._options));
  }

  private _messageReactions?: MessageReactions;
  get messageReactions(): MessageReactions {
    return (this._messageReactions ??= new MessageReactions(this._options));
  }

  private _answers?: Answers;
  get answers(): Answers {
    return (this._answers ??= new Answers(this._options));
  }

  private _webhookMessages?: WebhookMessages;
  get webhookMessages(): WebhookMessages {
    return (this._webhookMessages ??= new WebhookMessages(this._options));
  }

  private _webhooks?: Webhooks;
  get webhooks(): Webhooks {
    return (this._webhooks ??= new Webhooks(this._options));
  }

  private _autoModerationRules?: AutoModerationRules;
  get autoModerationRules(): AutoModerationRules {
    return (this._autoModerationRules ??= new AutoModerationRules(
      this._options,
    ));
  }

  private _guildThreads?: GuildThreads;
  get guildThreads(): GuildThreads {
    return (this._guildThreads ??= new GuildThreads(this._options));
  }

  private _guildsMembers?: GuildsMembers;
  get guildsMembers(): GuildsMembers {
    return (this._guildsMembers ??= new GuildsMembers(this._options));
  }

  private _guildMemberRoles?: GuildMemberRoles;
  get guildMemberRoles(): GuildMemberRoles {
    return (this._guildMemberRoles ??= new GuildMemberRoles(this._options));
  }

  private _applicationsCommands?: ApplicationsCommands;
  get applicationsCommands(): ApplicationsCommands {
    return (this._applicationsCommands ??= new ApplicationsCommands(
      this._options,
    ));
  }

  private _threadMembers?: ThreadMembers;
  get threadMembers(): ThreadMembers {
    return (this._threadMembers ??= new ThreadMembers(this._options));
  }

  private _channelPermissions?: ChannelPermissions;
  get channelPermissions(): ChannelPermissions {
    return (this._channelPermissions ??= new ChannelPermissions(this._options));
  }

  private _channelsRecipients?: ChannelsRecipients;
  get channelsRecipients(): ChannelsRecipients {
    return (this._channelsRecipients ??= new ChannelsRecipients(this._options));
  }

  private _guildTemplates?: GuildTemplates;
  get guildTemplates(): GuildTemplates {
    return (this._guildTemplates ??= new GuildTemplates(this._options));
  }

  private _guildSoundboardSounds?: GuildSoundboardSounds;
  get guildSoundboardSounds(): GuildSoundboardSounds {
    return (this._guildSoundboardSounds ??= new GuildSoundboardSounds(
      this._options,
    ));
  }

  private _guildsSoundboardSounds?: GuildsSoundboardSounds;
  get guildsSoundboardSounds(): GuildsSoundboardSounds {
    return (this._guildsSoundboardSounds ??= new GuildsSoundboardSounds(
      this._options,
    ));
  }

  private _guildScheduledEvents?: GuildScheduledEvents;
  get guildScheduledEvents(): GuildScheduledEvents {
    return (this._guildScheduledEvents ??= new GuildScheduledEvents(
      this._options,
    ));
  }

  private _scheduledEvents?: ScheduledEvents;
  get scheduledEvents(): ScheduledEvents {
    return (this._scheduledEvents ??= new ScheduledEvents(this._options));
  }

  private _guildIntegrations?: GuildIntegrations;
  get guildIntegrations(): GuildIntegrations {
    return (this._guildIntegrations ??= new GuildIntegrations(this._options));
  }

  private _guildOnboarding?: GuildOnboarding;
  get guildOnboarding(): GuildOnboarding {
    return (this._guildOnboarding ??= new GuildOnboarding(this._options));
  }

  private _guildBans?: GuildBans;
  get guildBans(): GuildBans {
    return (this._guildBans ??= new GuildBans(this._options));
  }

  private _guildStickers?: GuildStickers;
  get guildStickers(): GuildStickers {
    return (this._guildStickers ??= new GuildStickers(this._options));
  }

  private _guildsChannels?: GuildsChannels;
  get guildsChannels(): GuildsChannels {
    return (this._guildsChannels ??= new GuildsChannels(this._options));
  }

  private _guildMembers?: GuildMembers;
  get guildMembers(): GuildMembers {
    return (this._guildMembers ??= new GuildMembers(this._options));
  }

  private _guildVoiceRegions?: GuildVoiceRegions;
  get guildVoiceRegions(): GuildVoiceRegions {
    return (this._guildVoiceRegions ??= new GuildVoiceRegions(this._options));
  }

  private _guildEmojis?: GuildEmojis;
  get guildEmojis(): GuildEmojis {
    return (this._guildEmojis ??= new GuildEmojis(this._options));
  }

  private _guildWidgetSettings?: GuildWidgetSettings;
  get guildWidgetSettings(): GuildWidgetSettings {
    return (this._guildWidgetSettings ??= new GuildWidgetSettings(
      this._options,
    ));
  }

  private _guildRoles?: GuildRoles;
  get guildRoles(): GuildRoles {
    return (this._guildRoles ??= new GuildRoles(this._options));
  }

  private _stickers?: Stickers;
  get stickers(): Stickers {
    return (this._stickers ??= new Stickers(this._options));
  }

  private _invites?: Invites;
  get invites(): Invites {
    return (this._invites ??= new Invites(this._options));
  }
}
