workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Discord-OAS:
        inputs:
            - location: https://raw.githubusercontent.com/discord/discord-api-spec/refs/heads/main/specs/openapi.json
        overlays:
            - location: .speakeasy/fixes-overlay.yaml
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        output: .speakeasy/output-spec.yaml
        registry:
            location: registry.speakeasyapi.dev/ryan-blunden-l5y/ryan.blunden/discord-oas
targets:
    discord:
        target: typescript
        source: Discord-OAS
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/ryan-blunden-l5y/ryan.blunden/discord-oas-code-samples
            blocking: false
