/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type BulkSetGuildApplicationCommandsSecurity = {
  botToken?: string | undefined;
};

export type BulkSetGuildApplicationCommandsRequest = {
  applicationId: string;
  guildId: string;
  requestBody: Array<components.ApplicationCommandUpdateRequest> | null;
};

/** @internal */
export const BulkSetGuildApplicationCommandsSecurity$inboundSchema: z.ZodType<
  BulkSetGuildApplicationCommandsSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  BotToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "BotToken": "botToken",
  });
});

/** @internal */
export type BulkSetGuildApplicationCommandsSecurity$Outbound = {
  BotToken?: string | undefined;
};

/** @internal */
export const BulkSetGuildApplicationCommandsSecurity$outboundSchema: z.ZodType<
  BulkSetGuildApplicationCommandsSecurity$Outbound,
  z.ZodTypeDef,
  BulkSetGuildApplicationCommandsSecurity
> = z.object({
  botToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    botToken: "BotToken",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BulkSetGuildApplicationCommandsSecurity$ {
  /** @deprecated use `BulkSetGuildApplicationCommandsSecurity$inboundSchema` instead. */
  export const inboundSchema =
    BulkSetGuildApplicationCommandsSecurity$inboundSchema;
  /** @deprecated use `BulkSetGuildApplicationCommandsSecurity$outboundSchema` instead. */
  export const outboundSchema =
    BulkSetGuildApplicationCommandsSecurity$outboundSchema;
  /** @deprecated use `BulkSetGuildApplicationCommandsSecurity$Outbound` instead. */
  export type Outbound = BulkSetGuildApplicationCommandsSecurity$Outbound;
}

/** @internal */
export const BulkSetGuildApplicationCommandsRequest$inboundSchema: z.ZodType<
  BulkSetGuildApplicationCommandsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  application_id: z.string(),
  guild_id: z.string(),
  RequestBody: z.nullable(
    z.array(components.ApplicationCommandUpdateRequest$inboundSchema),
  ),
}).transform((v) => {
  return remap$(v, {
    "application_id": "applicationId",
    "guild_id": "guildId",
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type BulkSetGuildApplicationCommandsRequest$Outbound = {
  application_id: string;
  guild_id: string;
  RequestBody:
    | Array<components.ApplicationCommandUpdateRequest$Outbound>
    | null;
};

/** @internal */
export const BulkSetGuildApplicationCommandsRequest$outboundSchema: z.ZodType<
  BulkSetGuildApplicationCommandsRequest$Outbound,
  z.ZodTypeDef,
  BulkSetGuildApplicationCommandsRequest
> = z.object({
  applicationId: z.string(),
  guildId: z.string(),
  requestBody: z.nullable(
    z.array(components.ApplicationCommandUpdateRequest$outboundSchema),
  ),
}).transform((v) => {
  return remap$(v, {
    applicationId: "application_id",
    guildId: "guild_id",
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BulkSetGuildApplicationCommandsRequest$ {
  /** @deprecated use `BulkSetGuildApplicationCommandsRequest$inboundSchema` instead. */
  export const inboundSchema =
    BulkSetGuildApplicationCommandsRequest$inboundSchema;
  /** @deprecated use `BulkSetGuildApplicationCommandsRequest$outboundSchema` instead. */
  export const outboundSchema =
    BulkSetGuildApplicationCommandsRequest$outboundSchema;
  /** @deprecated use `BulkSetGuildApplicationCommandsRequest$Outbound` instead. */
  export type Outbound = BulkSetGuildApplicationCommandsRequest$Outbound;
}
