/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type BulkDeleteMessagesRequestBody = {
  messages: Array<string>;
};

export type BulkDeleteMessagesRequest = {
  channelId: string;
  requestBody: BulkDeleteMessagesRequestBody;
};

/** @internal */
export const BulkDeleteMessagesRequestBody$inboundSchema: z.ZodType<
  BulkDeleteMessagesRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  messages: z.array(z.string()),
});

/** @internal */
export type BulkDeleteMessagesRequestBody$Outbound = {
  messages: Array<string>;
};

/** @internal */
export const BulkDeleteMessagesRequestBody$outboundSchema: z.ZodType<
  BulkDeleteMessagesRequestBody$Outbound,
  z.ZodTypeDef,
  BulkDeleteMessagesRequestBody
> = z.object({
  messages: z.array(z.string()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BulkDeleteMessagesRequestBody$ {
  /** @deprecated use `BulkDeleteMessagesRequestBody$inboundSchema` instead. */
  export const inboundSchema = BulkDeleteMessagesRequestBody$inboundSchema;
  /** @deprecated use `BulkDeleteMessagesRequestBody$outboundSchema` instead. */
  export const outboundSchema = BulkDeleteMessagesRequestBody$outboundSchema;
  /** @deprecated use `BulkDeleteMessagesRequestBody$Outbound` instead. */
  export type Outbound = BulkDeleteMessagesRequestBody$Outbound;
}

/** @internal */
export const BulkDeleteMessagesRequest$inboundSchema: z.ZodType<
  BulkDeleteMessagesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  channel_id: z.string(),
  RequestBody: z.lazy(() => BulkDeleteMessagesRequestBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "channel_id": "channelId",
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type BulkDeleteMessagesRequest$Outbound = {
  channel_id: string;
  RequestBody: BulkDeleteMessagesRequestBody$Outbound;
};

/** @internal */
export const BulkDeleteMessagesRequest$outboundSchema: z.ZodType<
  BulkDeleteMessagesRequest$Outbound,
  z.ZodTypeDef,
  BulkDeleteMessagesRequest
> = z.object({
  channelId: z.string(),
  requestBody: z.lazy(() => BulkDeleteMessagesRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    channelId: "channel_id",
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BulkDeleteMessagesRequest$ {
  /** @deprecated use `BulkDeleteMessagesRequest$inboundSchema` instead. */
  export const inboundSchema = BulkDeleteMessagesRequest$inboundSchema;
  /** @deprecated use `BulkDeleteMessagesRequest$outboundSchema` instead. */
  export const outboundSchema = BulkDeleteMessagesRequest$outboundSchema;
  /** @deprecated use `BulkDeleteMessagesRequest$Outbound` instead. */
  export type Outbound = BulkDeleteMessagesRequest$Outbound;
}
