/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ConsumeEntitlementSecurity = {
  botToken?: string | undefined;
};

export type ConsumeEntitlementRequest = {
  applicationId: string;
  entitlementId: string;
};

/** @internal */
export const ConsumeEntitlementSecurity$inboundSchema: z.ZodType<
  ConsumeEntitlementSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  BotToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "BotToken": "botToken",
  });
});

/** @internal */
export type ConsumeEntitlementSecurity$Outbound = {
  BotToken?: string | undefined;
};

/** @internal */
export const ConsumeEntitlementSecurity$outboundSchema: z.ZodType<
  ConsumeEntitlementSecurity$Outbound,
  z.ZodTypeDef,
  ConsumeEntitlementSecurity
> = z.object({
  botToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    botToken: "BotToken",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsumeEntitlementSecurity$ {
  /** @deprecated use `ConsumeEntitlementSecurity$inboundSchema` instead. */
  export const inboundSchema = ConsumeEntitlementSecurity$inboundSchema;
  /** @deprecated use `ConsumeEntitlementSecurity$outboundSchema` instead. */
  export const outboundSchema = ConsumeEntitlementSecurity$outboundSchema;
  /** @deprecated use `ConsumeEntitlementSecurity$Outbound` instead. */
  export type Outbound = ConsumeEntitlementSecurity$Outbound;
}

export function consumeEntitlementSecurityToJSON(
  consumeEntitlementSecurity: ConsumeEntitlementSecurity,
): string {
  return JSON.stringify(
    ConsumeEntitlementSecurity$outboundSchema.parse(consumeEntitlementSecurity),
  );
}

export function consumeEntitlementSecurityFromJSON(
  jsonString: string,
): SafeParseResult<ConsumeEntitlementSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConsumeEntitlementSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConsumeEntitlementSecurity' from JSON`,
  );
}

/** @internal */
export const ConsumeEntitlementRequest$inboundSchema: z.ZodType<
  ConsumeEntitlementRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  application_id: z.string(),
  entitlement_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "application_id": "applicationId",
    "entitlement_id": "entitlementId",
  });
});

/** @internal */
export type ConsumeEntitlementRequest$Outbound = {
  application_id: string;
  entitlement_id: string;
};

/** @internal */
export const ConsumeEntitlementRequest$outboundSchema: z.ZodType<
  ConsumeEntitlementRequest$Outbound,
  z.ZodTypeDef,
  ConsumeEntitlementRequest
> = z.object({
  applicationId: z.string(),
  entitlementId: z.string(),
}).transform((v) => {
  return remap$(v, {
    applicationId: "application_id",
    entitlementId: "entitlement_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConsumeEntitlementRequest$ {
  /** @deprecated use `ConsumeEntitlementRequest$inboundSchema` instead. */
  export const inboundSchema = ConsumeEntitlementRequest$inboundSchema;
  /** @deprecated use `ConsumeEntitlementRequest$outboundSchema` instead. */
  export const outboundSchema = ConsumeEntitlementRequest$outboundSchema;
  /** @deprecated use `ConsumeEntitlementRequest$Outbound` instead. */
  export type Outbound = ConsumeEntitlementRequest$Outbound;
}

export function consumeEntitlementRequestToJSON(
  consumeEntitlementRequest: ConsumeEntitlementRequest,
): string {
  return JSON.stringify(
    ConsumeEntitlementRequest$outboundSchema.parse(consumeEntitlementRequest),
  );
}

export function consumeEntitlementRequestFromJSON(
  jsonString: string,
): SafeParseResult<ConsumeEntitlementRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConsumeEntitlementRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConsumeEntitlementRequest' from JSON`,
  );
}
