/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type CreateGuildSoundboardSoundRequest = {
  guildId: string;
  soundboardCreateRequest: components.SoundboardCreateRequest;
};

/** @internal */
export const CreateGuildSoundboardSoundRequest$inboundSchema: z.ZodType<
  CreateGuildSoundboardSoundRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  guild_id: z.string(),
  SoundboardCreateRequest: components.SoundboardCreateRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "guild_id": "guildId",
    "SoundboardCreateRequest": "soundboardCreateRequest",
  });
});

/** @internal */
export type CreateGuildSoundboardSoundRequest$Outbound = {
  guild_id: string;
  SoundboardCreateRequest: components.SoundboardCreateRequest$Outbound;
};

/** @internal */
export const CreateGuildSoundboardSoundRequest$outboundSchema: z.ZodType<
  CreateGuildSoundboardSoundRequest$Outbound,
  z.ZodTypeDef,
  CreateGuildSoundboardSoundRequest
> = z.object({
  guildId: z.string(),
  soundboardCreateRequest: components.SoundboardCreateRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    guildId: "guild_id",
    soundboardCreateRequest: "SoundboardCreateRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateGuildSoundboardSoundRequest$ {
  /** @deprecated use `CreateGuildSoundboardSoundRequest$inboundSchema` instead. */
  export const inboundSchema = CreateGuildSoundboardSoundRequest$inboundSchema;
  /** @deprecated use `CreateGuildSoundboardSoundRequest$outboundSchema` instead. */
  export const outboundSchema =
    CreateGuildSoundboardSoundRequest$outboundSchema;
  /** @deprecated use `CreateGuildSoundboardSoundRequest$Outbound` instead. */
  export type Outbound = CreateGuildSoundboardSoundRequest$Outbound;
}
