/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateGuildChannelRequest = {
  guildId: string;
  createGuildChannelRequest: components.CreateGuildChannelRequest;
};

/** @internal */
export const CreateGuildChannelRequest$inboundSchema: z.ZodType<
  CreateGuildChannelRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  guild_id: z.string(),
  CreateGuildChannelRequest: components.CreateGuildChannelRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "guild_id": "guildId",
    "CreateGuildChannelRequest": "createGuildChannelRequest",
  });
});

/** @internal */
export type CreateGuildChannelRequest$Outbound = {
  guild_id: string;
  CreateGuildChannelRequest: components.CreateGuildChannelRequest$Outbound;
};

/** @internal */
export const CreateGuildChannelRequest$outboundSchema: z.ZodType<
  CreateGuildChannelRequest$Outbound,
  z.ZodTypeDef,
  CreateGuildChannelRequest
> = z.object({
  guildId: z.string(),
  createGuildChannelRequest:
    components.CreateGuildChannelRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    guildId: "guild_id",
    createGuildChannelRequest: "CreateGuildChannelRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateGuildChannelRequest$ {
  /** @deprecated use `CreateGuildChannelRequest$inboundSchema` instead. */
  export const inboundSchema = CreateGuildChannelRequest$inboundSchema;
  /** @deprecated use `CreateGuildChannelRequest$outboundSchema` instead. */
  export const outboundSchema = CreateGuildChannelRequest$outboundSchema;
  /** @deprecated use `CreateGuildChannelRequest$Outbound` instead. */
  export type Outbound = CreateGuildChannelRequest$Outbound;
}

export function createGuildChannelRequestToJSON(
  createGuildChannelRequest: CreateGuildChannelRequest,
): string {
  return JSON.stringify(
    CreateGuildChannelRequest$outboundSchema.parse(createGuildChannelRequest),
  );
}

export function createGuildChannelRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateGuildChannelRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateGuildChannelRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateGuildChannelRequest' from JSON`,
  );
}
