/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteGuildMemberRoleRequest = {
  guildId: string;
  userId: string;
  roleId: string;
};

/** @internal */
export const DeleteGuildMemberRoleRequest$inboundSchema: z.ZodType<
  DeleteGuildMemberRoleRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  guild_id: z.string(),
  user_id: z.string(),
  role_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "guild_id": "guildId",
    "user_id": "userId",
    "role_id": "roleId",
  });
});

/** @internal */
export type DeleteGuildMemberRoleRequest$Outbound = {
  guild_id: string;
  user_id: string;
  role_id: string;
};

/** @internal */
export const DeleteGuildMemberRoleRequest$outboundSchema: z.ZodType<
  DeleteGuildMemberRoleRequest$Outbound,
  z.ZodTypeDef,
  DeleteGuildMemberRoleRequest
> = z.object({
  guildId: z.string(),
  userId: z.string(),
  roleId: z.string(),
}).transform((v) => {
  return remap$(v, {
    guildId: "guild_id",
    userId: "user_id",
    roleId: "role_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteGuildMemberRoleRequest$ {
  /** @deprecated use `DeleteGuildMemberRoleRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteGuildMemberRoleRequest$inboundSchema;
  /** @deprecated use `DeleteGuildMemberRoleRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteGuildMemberRoleRequest$outboundSchema;
  /** @deprecated use `DeleteGuildMemberRoleRequest$Outbound` instead. */
  export type Outbound = DeleteGuildMemberRoleRequest$Outbound;
}

export function deleteGuildMemberRoleRequestToJSON(
  deleteGuildMemberRoleRequest: DeleteGuildMemberRoleRequest,
): string {
  return JSON.stringify(
    DeleteGuildMemberRoleRequest$outboundSchema.parse(
      deleteGuildMemberRoleRequest,
    ),
  );
}

export function deleteGuildMemberRoleRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteGuildMemberRoleRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteGuildMemberRoleRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteGuildMemberRoleRequest' from JSON`,
  );
}
