/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type DeleteGuildMemberRequest = {
  guildId: string;
  userId: string;
};

/** @internal */
export const DeleteGuildMemberRequest$inboundSchema: z.ZodType<
  DeleteGuildMemberRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  guild_id: z.string(),
  user_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "guild_id": "guildId",
    "user_id": "userId",
  });
});

/** @internal */
export type DeleteGuildMemberRequest$Outbound = {
  guild_id: string;
  user_id: string;
};

/** @internal */
export const DeleteGuildMemberRequest$outboundSchema: z.ZodType<
  DeleteGuildMemberRequest$Outbound,
  z.ZodTypeDef,
  DeleteGuildMemberRequest
> = z.object({
  guildId: z.string(),
  userId: z.string(),
}).transform((v) => {
  return remap$(v, {
    guildId: "guild_id",
    userId: "user_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteGuildMemberRequest$ {
  /** @deprecated use `DeleteGuildMemberRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteGuildMemberRequest$inboundSchema;
  /** @deprecated use `DeleteGuildMemberRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteGuildMemberRequest$outboundSchema;
  /** @deprecated use `DeleteGuildMemberRequest$Outbound` instead. */
  export type Outbound = DeleteGuildMemberRequest$Outbound;
}
