/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteAllMessageReactionsRequest = {
  channelId: string;
  messageId: string;
};

/** @internal */
export const DeleteAllMessageReactionsRequest$inboundSchema: z.ZodType<
  DeleteAllMessageReactionsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  channel_id: z.string(),
  message_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "channel_id": "channelId",
    "message_id": "messageId",
  });
});

/** @internal */
export type DeleteAllMessageReactionsRequest$Outbound = {
  channel_id: string;
  message_id: string;
};

/** @internal */
export const DeleteAllMessageReactionsRequest$outboundSchema: z.ZodType<
  DeleteAllMessageReactionsRequest$Outbound,
  z.ZodTypeDef,
  DeleteAllMessageReactionsRequest
> = z.object({
  channelId: z.string(),
  messageId: z.string(),
}).transform((v) => {
  return remap$(v, {
    channelId: "channel_id",
    messageId: "message_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteAllMessageReactionsRequest$ {
  /** @deprecated use `DeleteAllMessageReactionsRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteAllMessageReactionsRequest$inboundSchema;
  /** @deprecated use `DeleteAllMessageReactionsRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteAllMessageReactionsRequest$outboundSchema;
  /** @deprecated use `DeleteAllMessageReactionsRequest$Outbound` instead. */
  export type Outbound = DeleteAllMessageReactionsRequest$Outbound;
}

export function deleteAllMessageReactionsRequestToJSON(
  deleteAllMessageReactionsRequest: DeleteAllMessageReactionsRequest,
): string {
  return JSON.stringify(
    DeleteAllMessageReactionsRequest$outboundSchema.parse(
      deleteAllMessageReactionsRequest,
    ),
  );
}

export function deleteAllMessageReactionsRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteAllMessageReactionsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteAllMessageReactionsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteAllMessageReactionsRequest' from JSON`,
  );
}
