/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type DeleteWebhookMessageSecurity = {
  botToken?: string | undefined;
};

export type DeleteWebhookMessageRequest = {
  webhookId: string;
  webhookToken: string;
  messageId: string;
  threadId?: string | undefined;
};

/** @internal */
export const DeleteWebhookMessageSecurity$inboundSchema: z.ZodType<
  DeleteWebhookMessageSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  BotToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "BotToken": "botToken",
  });
});

/** @internal */
export type DeleteWebhookMessageSecurity$Outbound = {
  BotToken?: string | undefined;
};

/** @internal */
export const DeleteWebhookMessageSecurity$outboundSchema: z.ZodType<
  DeleteWebhookMessageSecurity$Outbound,
  z.ZodTypeDef,
  DeleteWebhookMessageSecurity
> = z.object({
  botToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    botToken: "BotToken",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteWebhookMessageSecurity$ {
  /** @deprecated use `DeleteWebhookMessageSecurity$inboundSchema` instead. */
  export const inboundSchema = DeleteWebhookMessageSecurity$inboundSchema;
  /** @deprecated use `DeleteWebhookMessageSecurity$outboundSchema` instead. */
  export const outboundSchema = DeleteWebhookMessageSecurity$outboundSchema;
  /** @deprecated use `DeleteWebhookMessageSecurity$Outbound` instead. */
  export type Outbound = DeleteWebhookMessageSecurity$Outbound;
}

/** @internal */
export const DeleteWebhookMessageRequest$inboundSchema: z.ZodType<
  DeleteWebhookMessageRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  webhook_id: z.string(),
  webhook_token: z.string(),
  message_id: z.string(),
  thread_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "webhook_id": "webhookId",
    "webhook_token": "webhookToken",
    "message_id": "messageId",
    "thread_id": "threadId",
  });
});

/** @internal */
export type DeleteWebhookMessageRequest$Outbound = {
  webhook_id: string;
  webhook_token: string;
  message_id: string;
  thread_id?: string | undefined;
};

/** @internal */
export const DeleteWebhookMessageRequest$outboundSchema: z.ZodType<
  DeleteWebhookMessageRequest$Outbound,
  z.ZodTypeDef,
  DeleteWebhookMessageRequest
> = z.object({
  webhookId: z.string(),
  webhookToken: z.string(),
  messageId: z.string(),
  threadId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    webhookId: "webhook_id",
    webhookToken: "webhook_token",
    messageId: "message_id",
    threadId: "thread_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteWebhookMessageRequest$ {
  /** @deprecated use `DeleteWebhookMessageRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteWebhookMessageRequest$inboundSchema;
  /** @deprecated use `DeleteWebhookMessageRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteWebhookMessageRequest$outboundSchema;
  /** @deprecated use `DeleteWebhookMessageRequest$Outbound` instead. */
  export type Outbound = DeleteWebhookMessageRequest$Outbound;
}
