/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type DeleteGuildEmojiRequest = {
  guildId: string;
  emojiId: string;
};

/** @internal */
export const DeleteGuildEmojiRequest$inboundSchema: z.ZodType<
  DeleteGuildEmojiRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  guild_id: z.string(),
  emoji_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "guild_id": "guildId",
    "emoji_id": "emojiId",
  });
});

/** @internal */
export type DeleteGuildEmojiRequest$Outbound = {
  guild_id: string;
  emoji_id: string;
};

/** @internal */
export const DeleteGuildEmojiRequest$outboundSchema: z.ZodType<
  DeleteGuildEmojiRequest$Outbound,
  z.ZodTypeDef,
  DeleteGuildEmojiRequest
> = z.object({
  guildId: z.string(),
  emojiId: z.string(),
}).transform((v) => {
  return remap$(v, {
    guildId: "guild_id",
    emojiId: "emoji_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteGuildEmojiRequest$ {
  /** @deprecated use `DeleteGuildEmojiRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteGuildEmojiRequest$inboundSchema;
  /** @deprecated use `DeleteGuildEmojiRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteGuildEmojiRequest$outboundSchema;
  /** @deprecated use `DeleteGuildEmojiRequest$Outbound` instead. */
  export type Outbound = DeleteGuildEmojiRequest$Outbound;
}
