/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type ExecuteGithubCompatibleWebhookSecurity = {
  botToken?: string | undefined;
};

export type ExecuteGithubCompatibleWebhookRequest = {
  webhookId: string;
  webhookToken: string;
  wait?: boolean | undefined;
  threadId?: string | undefined;
  githubWebhook: components.GithubWebhook;
};

/** @internal */
export const ExecuteGithubCompatibleWebhookSecurity$inboundSchema: z.ZodType<
  ExecuteGithubCompatibleWebhookSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  BotToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "BotToken": "botToken",
  });
});

/** @internal */
export type ExecuteGithubCompatibleWebhookSecurity$Outbound = {
  BotToken?: string | undefined;
};

/** @internal */
export const ExecuteGithubCompatibleWebhookSecurity$outboundSchema: z.ZodType<
  ExecuteGithubCompatibleWebhookSecurity$Outbound,
  z.ZodTypeDef,
  ExecuteGithubCompatibleWebhookSecurity
> = z.object({
  botToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    botToken: "BotToken",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ExecuteGithubCompatibleWebhookSecurity$ {
  /** @deprecated use `ExecuteGithubCompatibleWebhookSecurity$inboundSchema` instead. */
  export const inboundSchema =
    ExecuteGithubCompatibleWebhookSecurity$inboundSchema;
  /** @deprecated use `ExecuteGithubCompatibleWebhookSecurity$outboundSchema` instead. */
  export const outboundSchema =
    ExecuteGithubCompatibleWebhookSecurity$outboundSchema;
  /** @deprecated use `ExecuteGithubCompatibleWebhookSecurity$Outbound` instead. */
  export type Outbound = ExecuteGithubCompatibleWebhookSecurity$Outbound;
}

/** @internal */
export const ExecuteGithubCompatibleWebhookRequest$inboundSchema: z.ZodType<
  ExecuteGithubCompatibleWebhookRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  webhook_id: z.string(),
  webhook_token: z.string(),
  wait: z.boolean().optional(),
  thread_id: z.string().optional(),
  GithubWebhook: components.GithubWebhook$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "webhook_id": "webhookId",
    "webhook_token": "webhookToken",
    "thread_id": "threadId",
    "GithubWebhook": "githubWebhook",
  });
});

/** @internal */
export type ExecuteGithubCompatibleWebhookRequest$Outbound = {
  webhook_id: string;
  webhook_token: string;
  wait?: boolean | undefined;
  thread_id?: string | undefined;
  GithubWebhook: components.GithubWebhook$Outbound;
};

/** @internal */
export const ExecuteGithubCompatibleWebhookRequest$outboundSchema: z.ZodType<
  ExecuteGithubCompatibleWebhookRequest$Outbound,
  z.ZodTypeDef,
  ExecuteGithubCompatibleWebhookRequest
> = z.object({
  webhookId: z.string(),
  webhookToken: z.string(),
  wait: z.boolean().optional(),
  threadId: z.string().optional(),
  githubWebhook: components.GithubWebhook$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    webhookId: "webhook_id",
    webhookToken: "webhook_token",
    threadId: "thread_id",
    githubWebhook: "GithubWebhook",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ExecuteGithubCompatibleWebhookRequest$ {
  /** @deprecated use `ExecuteGithubCompatibleWebhookRequest$inboundSchema` instead. */
  export const inboundSchema =
    ExecuteGithubCompatibleWebhookRequest$inboundSchema;
  /** @deprecated use `ExecuteGithubCompatibleWebhookRequest$outboundSchema` instead. */
  export const outboundSchema =
    ExecuteGithubCompatibleWebhookRequest$outboundSchema;
  /** @deprecated use `ExecuteGithubCompatibleWebhookRequest$Outbound` instead. */
  export type Outbound = ExecuteGithubCompatibleWebhookRequest$Outbound;
}
