/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ExecuteSlackCompatibleWebhookSecurity = {
  botToken?: string | undefined;
};

export type ExecuteSlackCompatibleWebhookRequest = {
  webhookId: string;
  webhookToken: string;
  wait?: boolean | undefined;
  threadId?: string | undefined;
  slackWebhook: components.SlackWebhook;
};

/** @internal */
export const ExecuteSlackCompatibleWebhookSecurity$inboundSchema: z.ZodType<
  ExecuteSlackCompatibleWebhookSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  BotToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "BotToken": "botToken",
  });
});

/** @internal */
export type ExecuteSlackCompatibleWebhookSecurity$Outbound = {
  BotToken?: string | undefined;
};

/** @internal */
export const ExecuteSlackCompatibleWebhookSecurity$outboundSchema: z.ZodType<
  ExecuteSlackCompatibleWebhookSecurity$Outbound,
  z.ZodTypeDef,
  ExecuteSlackCompatibleWebhookSecurity
> = z.object({
  botToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    botToken: "BotToken",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ExecuteSlackCompatibleWebhookSecurity$ {
  /** @deprecated use `ExecuteSlackCompatibleWebhookSecurity$inboundSchema` instead. */
  export const inboundSchema =
    ExecuteSlackCompatibleWebhookSecurity$inboundSchema;
  /** @deprecated use `ExecuteSlackCompatibleWebhookSecurity$outboundSchema` instead. */
  export const outboundSchema =
    ExecuteSlackCompatibleWebhookSecurity$outboundSchema;
  /** @deprecated use `ExecuteSlackCompatibleWebhookSecurity$Outbound` instead. */
  export type Outbound = ExecuteSlackCompatibleWebhookSecurity$Outbound;
}

export function executeSlackCompatibleWebhookSecurityToJSON(
  executeSlackCompatibleWebhookSecurity: ExecuteSlackCompatibleWebhookSecurity,
): string {
  return JSON.stringify(
    ExecuteSlackCompatibleWebhookSecurity$outboundSchema.parse(
      executeSlackCompatibleWebhookSecurity,
    ),
  );
}

export function executeSlackCompatibleWebhookSecurityFromJSON(
  jsonString: string,
): SafeParseResult<ExecuteSlackCompatibleWebhookSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ExecuteSlackCompatibleWebhookSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExecuteSlackCompatibleWebhookSecurity' from JSON`,
  );
}

/** @internal */
export const ExecuteSlackCompatibleWebhookRequest$inboundSchema: z.ZodType<
  ExecuteSlackCompatibleWebhookRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  webhook_id: z.string(),
  webhook_token: z.string(),
  wait: z.boolean().optional(),
  thread_id: z.string().optional(),
  SlackWebhook: components.SlackWebhook$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "webhook_id": "webhookId",
    "webhook_token": "webhookToken",
    "thread_id": "threadId",
    "SlackWebhook": "slackWebhook",
  });
});

/** @internal */
export type ExecuteSlackCompatibleWebhookRequest$Outbound = {
  webhook_id: string;
  webhook_token: string;
  wait?: boolean | undefined;
  thread_id?: string | undefined;
  SlackWebhook: components.SlackWebhook$Outbound;
};

/** @internal */
export const ExecuteSlackCompatibleWebhookRequest$outboundSchema: z.ZodType<
  ExecuteSlackCompatibleWebhookRequest$Outbound,
  z.ZodTypeDef,
  ExecuteSlackCompatibleWebhookRequest
> = z.object({
  webhookId: z.string(),
  webhookToken: z.string(),
  wait: z.boolean().optional(),
  threadId: z.string().optional(),
  slackWebhook: components.SlackWebhook$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    webhookId: "webhook_id",
    webhookToken: "webhook_token",
    threadId: "thread_id",
    slackWebhook: "SlackWebhook",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ExecuteSlackCompatibleWebhookRequest$ {
  /** @deprecated use `ExecuteSlackCompatibleWebhookRequest$inboundSchema` instead. */
  export const inboundSchema =
    ExecuteSlackCompatibleWebhookRequest$inboundSchema;
  /** @deprecated use `ExecuteSlackCompatibleWebhookRequest$outboundSchema` instead. */
  export const outboundSchema =
    ExecuteSlackCompatibleWebhookRequest$outboundSchema;
  /** @deprecated use `ExecuteSlackCompatibleWebhookRequest$Outbound` instead. */
  export type Outbound = ExecuteSlackCompatibleWebhookRequest$Outbound;
}

export function executeSlackCompatibleWebhookRequestToJSON(
  executeSlackCompatibleWebhookRequest: ExecuteSlackCompatibleWebhookRequest,
): string {
  return JSON.stringify(
    ExecuteSlackCompatibleWebhookRequest$outboundSchema.parse(
      executeSlackCompatibleWebhookRequest,
    ),
  );
}

export function executeSlackCompatibleWebhookRequestFromJSON(
  jsonString: string,
): SafeParseResult<ExecuteSlackCompatibleWebhookRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ExecuteSlackCompatibleWebhookRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExecuteSlackCompatibleWebhookRequest' from JSON`,
  );
}
