/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type GetAutoModerationRuleRequest = {
  guildId: string;
  ruleId: string;
};

/**
 * 200 response for get_auto_moderation_rule
 */
export type GetAutoModerationRuleResponseBody =
  | components.DefaultKeywordRuleResponse
  | components.KeywordRuleResponse
  | components.MLSpamRuleResponse
  | components.MentionSpamRuleResponse
  | components.SpamLinkRuleResponse;

/** @internal */
export const GetAutoModerationRuleRequest$inboundSchema: z.ZodType<
  GetAutoModerationRuleRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  guild_id: z.string(),
  rule_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "guild_id": "guildId",
    "rule_id": "ruleId",
  });
});

/** @internal */
export type GetAutoModerationRuleRequest$Outbound = {
  guild_id: string;
  rule_id: string;
};

/** @internal */
export const GetAutoModerationRuleRequest$outboundSchema: z.ZodType<
  GetAutoModerationRuleRequest$Outbound,
  z.ZodTypeDef,
  GetAutoModerationRuleRequest
> = z.object({
  guildId: z.string(),
  ruleId: z.string(),
}).transform((v) => {
  return remap$(v, {
    guildId: "guild_id",
    ruleId: "rule_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAutoModerationRuleRequest$ {
  /** @deprecated use `GetAutoModerationRuleRequest$inboundSchema` instead. */
  export const inboundSchema = GetAutoModerationRuleRequest$inboundSchema;
  /** @deprecated use `GetAutoModerationRuleRequest$outboundSchema` instead. */
  export const outboundSchema = GetAutoModerationRuleRequest$outboundSchema;
  /** @deprecated use `GetAutoModerationRuleRequest$Outbound` instead. */
  export type Outbound = GetAutoModerationRuleRequest$Outbound;
}

/** @internal */
export const GetAutoModerationRuleResponseBody$inboundSchema: z.ZodType<
  GetAutoModerationRuleResponseBody,
  z.ZodTypeDef,
  unknown
> = z.union([
  components.DefaultKeywordRuleResponse$inboundSchema,
  components.KeywordRuleResponse$inboundSchema,
  components.MLSpamRuleResponse$inboundSchema,
  components.MentionSpamRuleResponse$inboundSchema,
  components.SpamLinkRuleResponse$inboundSchema,
]);

/** @internal */
export type GetAutoModerationRuleResponseBody$Outbound =
  | components.DefaultKeywordRuleResponse$Outbound
  | components.KeywordRuleResponse$Outbound
  | components.MLSpamRuleResponse$Outbound
  | components.MentionSpamRuleResponse$Outbound
  | components.SpamLinkRuleResponse$Outbound;

/** @internal */
export const GetAutoModerationRuleResponseBody$outboundSchema: z.ZodType<
  GetAutoModerationRuleResponseBody$Outbound,
  z.ZodTypeDef,
  GetAutoModerationRuleResponseBody
> = z.union([
  components.DefaultKeywordRuleResponse$outboundSchema,
  components.KeywordRuleResponse$outboundSchema,
  components.MLSpamRuleResponse$outboundSchema,
  components.MentionSpamRuleResponse$outboundSchema,
  components.SpamLinkRuleResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAutoModerationRuleResponseBody$ {
  /** @deprecated use `GetAutoModerationRuleResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetAutoModerationRuleResponseBody$inboundSchema;
  /** @deprecated use `GetAutoModerationRuleResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    GetAutoModerationRuleResponseBody$outboundSchema;
  /** @deprecated use `GetAutoModerationRuleResponseBody$Outbound` instead. */
  export type Outbound = GetAutoModerationRuleResponseBody$Outbound;
}
