/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetAnswerVotersRequest = {
  channelId: string;
  messageId: string;
  answerId: number;
  after?: string | undefined;
  limit?: number | undefined;
};

/** @internal */
export const GetAnswerVotersRequest$inboundSchema: z.ZodType<
  GetAnswerVotersRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  channel_id: z.string(),
  message_id: z.string(),
  answer_id: z.number().int(),
  after: z.string().optional(),
  limit: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "channel_id": "channelId",
    "message_id": "messageId",
    "answer_id": "answerId",
  });
});

/** @internal */
export type GetAnswerVotersRequest$Outbound = {
  channel_id: string;
  message_id: string;
  answer_id: number;
  after?: string | undefined;
  limit?: number | undefined;
};

/** @internal */
export const GetAnswerVotersRequest$outboundSchema: z.ZodType<
  GetAnswerVotersRequest$Outbound,
  z.ZodTypeDef,
  GetAnswerVotersRequest
> = z.object({
  channelId: z.string(),
  messageId: z.string(),
  answerId: z.number().int(),
  after: z.string().optional(),
  limit: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    channelId: "channel_id",
    messageId: "message_id",
    answerId: "answer_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAnswerVotersRequest$ {
  /** @deprecated use `GetAnswerVotersRequest$inboundSchema` instead. */
  export const inboundSchema = GetAnswerVotersRequest$inboundSchema;
  /** @deprecated use `GetAnswerVotersRequest$outboundSchema` instead. */
  export const outboundSchema = GetAnswerVotersRequest$outboundSchema;
  /** @deprecated use `GetAnswerVotersRequest$Outbound` instead. */
  export type Outbound = GetAnswerVotersRequest$Outbound;
}
