/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetApplicationRoleConnectionsMetadataRequest = {
  applicationId: string;
};

/** @internal */
export const GetApplicationRoleConnectionsMetadataRequest$inboundSchema:
  z.ZodType<
    GetApplicationRoleConnectionsMetadataRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    application_id: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "application_id": "applicationId",
    });
  });

/** @internal */
export type GetApplicationRoleConnectionsMetadataRequest$Outbound = {
  application_id: string;
};

/** @internal */
export const GetApplicationRoleConnectionsMetadataRequest$outboundSchema:
  z.ZodType<
    GetApplicationRoleConnectionsMetadataRequest$Outbound,
    z.ZodTypeDef,
    GetApplicationRoleConnectionsMetadataRequest
  > = z.object({
    applicationId: z.string(),
  }).transform((v) => {
    return remap$(v, {
      applicationId: "application_id",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetApplicationRoleConnectionsMetadataRequest$ {
  /** @deprecated use `GetApplicationRoleConnectionsMetadataRequest$inboundSchema` instead. */
  export const inboundSchema =
    GetApplicationRoleConnectionsMetadataRequest$inboundSchema;
  /** @deprecated use `GetApplicationRoleConnectionsMetadataRequest$outboundSchema` instead. */
  export const outboundSchema =
    GetApplicationRoleConnectionsMetadataRequest$outboundSchema;
  /** @deprecated use `GetApplicationRoleConnectionsMetadataRequest$Outbound` instead. */
  export type Outbound = GetApplicationRoleConnectionsMetadataRequest$Outbound;
}

export function getApplicationRoleConnectionsMetadataRequestToJSON(
  getApplicationRoleConnectionsMetadataRequest:
    GetApplicationRoleConnectionsMetadataRequest,
): string {
  return JSON.stringify(
    GetApplicationRoleConnectionsMetadataRequest$outboundSchema.parse(
      getApplicationRoleConnectionsMetadataRequest,
    ),
  );
}

export function getApplicationRoleConnectionsMetadataRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  GetApplicationRoleConnectionsMetadataRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetApplicationRoleConnectionsMetadataRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetApplicationRoleConnectionsMetadataRequest' from JSON`,
  );
}
