/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetGuildNewMemberWelcomeRequest = {
  guildId: string;
};

/** @internal */
export const GetGuildNewMemberWelcomeRequest$inboundSchema: z.ZodType<
  GetGuildNewMemberWelcomeRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  guild_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "guild_id": "guildId",
  });
});

/** @internal */
export type GetGuildNewMemberWelcomeRequest$Outbound = {
  guild_id: string;
};

/** @internal */
export const GetGuildNewMemberWelcomeRequest$outboundSchema: z.ZodType<
  GetGuildNewMemberWelcomeRequest$Outbound,
  z.ZodTypeDef,
  GetGuildNewMemberWelcomeRequest
> = z.object({
  guildId: z.string(),
}).transform((v) => {
  return remap$(v, {
    guildId: "guild_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetGuildNewMemberWelcomeRequest$ {
  /** @deprecated use `GetGuildNewMemberWelcomeRequest$inboundSchema` instead. */
  export const inboundSchema = GetGuildNewMemberWelcomeRequest$inboundSchema;
  /** @deprecated use `GetGuildNewMemberWelcomeRequest$outboundSchema` instead. */
  export const outboundSchema = GetGuildNewMemberWelcomeRequest$outboundSchema;
  /** @deprecated use `GetGuildNewMemberWelcomeRequest$Outbound` instead. */
  export type Outbound = GetGuildNewMemberWelcomeRequest$Outbound;
}
