/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetGuildWelcomeScreenRequest = {
  guildId: string;
};

/** @internal */
export const GetGuildWelcomeScreenRequest$inboundSchema: z.ZodType<
  GetGuildWelcomeScreenRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  guild_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "guild_id": "guildId",
  });
});

/** @internal */
export type GetGuildWelcomeScreenRequest$Outbound = {
  guild_id: string;
};

/** @internal */
export const GetGuildWelcomeScreenRequest$outboundSchema: z.ZodType<
  GetGuildWelcomeScreenRequest$Outbound,
  z.ZodTypeDef,
  GetGuildWelcomeScreenRequest
> = z.object({
  guildId: z.string(),
}).transform((v) => {
  return remap$(v, {
    guildId: "guild_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetGuildWelcomeScreenRequest$ {
  /** @deprecated use `GetGuildWelcomeScreenRequest$inboundSchema` instead. */
  export const inboundSchema = GetGuildWelcomeScreenRequest$inboundSchema;
  /** @deprecated use `GetGuildWelcomeScreenRequest$outboundSchema` instead. */
  export const outboundSchema = GetGuildWelcomeScreenRequest$outboundSchema;
  /** @deprecated use `GetGuildWelcomeScreenRequest$Outbound` instead. */
  export type Outbound = GetGuildWelcomeScreenRequest$Outbound;
}
