/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type LeaveGuildRequest = {
  guildId: string;
};

/** @internal */
export const LeaveGuildRequest$inboundSchema: z.ZodType<
  LeaveGuildRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  guild_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "guild_id": "guildId",
  });
});

/** @internal */
export type LeaveGuildRequest$Outbound = {
  guild_id: string;
};

/** @internal */
export const LeaveGuildRequest$outboundSchema: z.ZodType<
  LeaveGuildRequest$Outbound,
  z.ZodTypeDef,
  LeaveGuildRequest
> = z.object({
  guildId: z.string(),
}).transform((v) => {
  return remap$(v, {
    guildId: "guild_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LeaveGuildRequest$ {
  /** @deprecated use `LeaveGuildRequest$inboundSchema` instead. */
  export const inboundSchema = LeaveGuildRequest$inboundSchema;
  /** @deprecated use `LeaveGuildRequest$outboundSchema` instead. */
  export const outboundSchema = LeaveGuildRequest$outboundSchema;
  /** @deprecated use `LeaveGuildRequest$Outbound` instead. */
  export type Outbound = LeaveGuildRequest$Outbound;
}
