/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListGuildVoiceRegionsRequest = {
  guildId: string;
};

/** @internal */
export const ListGuildVoiceRegionsRequest$inboundSchema: z.ZodType<
  ListGuildVoiceRegionsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  guild_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "guild_id": "guildId",
  });
});

/** @internal */
export type ListGuildVoiceRegionsRequest$Outbound = {
  guild_id: string;
};

/** @internal */
export const ListGuildVoiceRegionsRequest$outboundSchema: z.ZodType<
  ListGuildVoiceRegionsRequest$Outbound,
  z.ZodTypeDef,
  ListGuildVoiceRegionsRequest
> = z.object({
  guildId: z.string(),
}).transform((v) => {
  return remap$(v, {
    guildId: "guild_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListGuildVoiceRegionsRequest$ {
  /** @deprecated use `ListGuildVoiceRegionsRequest$inboundSchema` instead. */
  export const inboundSchema = ListGuildVoiceRegionsRequest$inboundSchema;
  /** @deprecated use `ListGuildVoiceRegionsRequest$outboundSchema` instead. */
  export const outboundSchema = ListGuildVoiceRegionsRequest$outboundSchema;
  /** @deprecated use `ListGuildVoiceRegionsRequest$Outbound` instead. */
  export type Outbound = ListGuildVoiceRegionsRequest$Outbound;
}

export function listGuildVoiceRegionsRequestToJSON(
  listGuildVoiceRegionsRequest: ListGuildVoiceRegionsRequest,
): string {
  return JSON.stringify(
    ListGuildVoiceRegionsRequest$outboundSchema.parse(
      listGuildVoiceRegionsRequest,
    ),
  );
}

export function listGuildVoiceRegionsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListGuildVoiceRegionsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListGuildVoiceRegionsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListGuildVoiceRegionsRequest' from JSON`,
  );
}
