/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type ListGuildRolesRequest = {
  guildId: string;
};

/** @internal */
export const ListGuildRolesRequest$inboundSchema: z.ZodType<
  ListGuildRolesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  guild_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "guild_id": "guildId",
  });
});

/** @internal */
export type ListGuildRolesRequest$Outbound = {
  guild_id: string;
};

/** @internal */
export const ListGuildRolesRequest$outboundSchema: z.ZodType<
  ListGuildRolesRequest$Outbound,
  z.ZodTypeDef,
  ListGuildRolesRequest
> = z.object({
  guildId: z.string(),
}).transform((v) => {
  return remap$(v, {
    guildId: "guild_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListGuildRolesRequest$ {
  /** @deprecated use `ListGuildRolesRequest$inboundSchema` instead. */
  export const inboundSchema = ListGuildRolesRequest$inboundSchema;
  /** @deprecated use `ListGuildRolesRequest$outboundSchema` instead. */
  export const outboundSchema = ListGuildRolesRequest$outboundSchema;
  /** @deprecated use `ListGuildRolesRequest$Outbound` instead. */
  export type Outbound = ListGuildRolesRequest$Outbound;
}
