/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type ListApplicationEmojisRequest = {
  applicationId: string;
};

/** @internal */
export const ListApplicationEmojisRequest$inboundSchema: z.ZodType<
  ListApplicationEmojisRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  application_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "application_id": "applicationId",
  });
});

/** @internal */
export type ListApplicationEmojisRequest$Outbound = {
  application_id: string;
};

/** @internal */
export const ListApplicationEmojisRequest$outboundSchema: z.ZodType<
  ListApplicationEmojisRequest$Outbound,
  z.ZodTypeDef,
  ListApplicationEmojisRequest
> = z.object({
  applicationId: z.string(),
}).transform((v) => {
  return remap$(v, {
    applicationId: "application_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListApplicationEmojisRequest$ {
  /** @deprecated use `ListApplicationEmojisRequest$inboundSchema` instead. */
  export const inboundSchema = ListApplicationEmojisRequest$inboundSchema;
  /** @deprecated use `ListApplicationEmojisRequest$outboundSchema` instead. */
  export const outboundSchema = ListApplicationEmojisRequest$outboundSchema;
  /** @deprecated use `ListApplicationEmojisRequest$Outbound` instead. */
  export type Outbound = ListApplicationEmojisRequest$Outbound;
}
