/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type TriggerTypingIndicatorRequest = {
  channelId: string;
};

/** @internal */
export const TriggerTypingIndicatorRequest$inboundSchema: z.ZodType<
  TriggerTypingIndicatorRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  channel_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "channel_id": "channelId",
  });
});

/** @internal */
export type TriggerTypingIndicatorRequest$Outbound = {
  channel_id: string;
};

/** @internal */
export const TriggerTypingIndicatorRequest$outboundSchema: z.ZodType<
  TriggerTypingIndicatorRequest$Outbound,
  z.ZodTypeDef,
  TriggerTypingIndicatorRequest
> = z.object({
  channelId: z.string(),
}).transform((v) => {
  return remap$(v, {
    channelId: "channel_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TriggerTypingIndicatorRequest$ {
  /** @deprecated use `TriggerTypingIndicatorRequest$inboundSchema` instead. */
  export const inboundSchema = TriggerTypingIndicatorRequest$inboundSchema;
  /** @deprecated use `TriggerTypingIndicatorRequest$outboundSchema` instead. */
  export const outboundSchema = TriggerTypingIndicatorRequest$outboundSchema;
  /** @deprecated use `TriggerTypingIndicatorRequest$Outbound` instead. */
  export type Outbound = TriggerTypingIndicatorRequest$Outbound;
}
