/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UnpinMessageRequest = {
  channelId: string;
  messageId: string;
};

/** @internal */
export const UnpinMessageRequest$inboundSchema: z.ZodType<
  UnpinMessageRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  channel_id: z.string(),
  message_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "channel_id": "channelId",
    "message_id": "messageId",
  });
});

/** @internal */
export type UnpinMessageRequest$Outbound = {
  channel_id: string;
  message_id: string;
};

/** @internal */
export const UnpinMessageRequest$outboundSchema: z.ZodType<
  UnpinMessageRequest$Outbound,
  z.ZodTypeDef,
  UnpinMessageRequest
> = z.object({
  channelId: z.string(),
  messageId: z.string(),
}).transform((v) => {
  return remap$(v, {
    channelId: "channel_id",
    messageId: "message_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnpinMessageRequest$ {
  /** @deprecated use `UnpinMessageRequest$inboundSchema` instead. */
  export const inboundSchema = UnpinMessageRequest$inboundSchema;
  /** @deprecated use `UnpinMessageRequest$outboundSchema` instead. */
  export const outboundSchema = UnpinMessageRequest$outboundSchema;
  /** @deprecated use `UnpinMessageRequest$Outbound` instead. */
  export type Outbound = UnpinMessageRequest$Outbound;
}

export function unpinMessageRequestToJSON(
  unpinMessageRequest: UnpinMessageRequest,
): string {
  return JSON.stringify(
    UnpinMessageRequest$outboundSchema.parse(unpinMessageRequest),
  );
}

export function unpinMessageRequestFromJSON(
  jsonString: string,
): SafeParseResult<UnpinMessageRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UnpinMessageRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UnpinMessageRequest' from JSON`,
  );
}
