/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type UpdateGuildApplicationCommandSecurity = {
  botToken?: string | undefined;
};

export type UpdateGuildApplicationCommandRequest = {
  applicationId: string;
  guildId: string;
  commandId: string;
  applicationCommandPatchRequestPartial:
    components.ApplicationCommandPatchRequestPartial;
};

/** @internal */
export const UpdateGuildApplicationCommandSecurity$inboundSchema: z.ZodType<
  UpdateGuildApplicationCommandSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  BotToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "BotToken": "botToken",
  });
});

/** @internal */
export type UpdateGuildApplicationCommandSecurity$Outbound = {
  BotToken?: string | undefined;
};

/** @internal */
export const UpdateGuildApplicationCommandSecurity$outboundSchema: z.ZodType<
  UpdateGuildApplicationCommandSecurity$Outbound,
  z.ZodTypeDef,
  UpdateGuildApplicationCommandSecurity
> = z.object({
  botToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    botToken: "BotToken",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateGuildApplicationCommandSecurity$ {
  /** @deprecated use `UpdateGuildApplicationCommandSecurity$inboundSchema` instead. */
  export const inboundSchema =
    UpdateGuildApplicationCommandSecurity$inboundSchema;
  /** @deprecated use `UpdateGuildApplicationCommandSecurity$outboundSchema` instead. */
  export const outboundSchema =
    UpdateGuildApplicationCommandSecurity$outboundSchema;
  /** @deprecated use `UpdateGuildApplicationCommandSecurity$Outbound` instead. */
  export type Outbound = UpdateGuildApplicationCommandSecurity$Outbound;
}

/** @internal */
export const UpdateGuildApplicationCommandRequest$inboundSchema: z.ZodType<
  UpdateGuildApplicationCommandRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  application_id: z.string(),
  guild_id: z.string(),
  command_id: z.string(),
  ApplicationCommandPatchRequestPartial:
    components.ApplicationCommandPatchRequestPartial$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "application_id": "applicationId",
    "guild_id": "guildId",
    "command_id": "commandId",
    "ApplicationCommandPatchRequestPartial":
      "applicationCommandPatchRequestPartial",
  });
});

/** @internal */
export type UpdateGuildApplicationCommandRequest$Outbound = {
  application_id: string;
  guild_id: string;
  command_id: string;
  ApplicationCommandPatchRequestPartial:
    components.ApplicationCommandPatchRequestPartial$Outbound;
};

/** @internal */
export const UpdateGuildApplicationCommandRequest$outboundSchema: z.ZodType<
  UpdateGuildApplicationCommandRequest$Outbound,
  z.ZodTypeDef,
  UpdateGuildApplicationCommandRequest
> = z.object({
  applicationId: z.string(),
  guildId: z.string(),
  commandId: z.string(),
  applicationCommandPatchRequestPartial:
    components.ApplicationCommandPatchRequestPartial$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    applicationId: "application_id",
    guildId: "guild_id",
    commandId: "command_id",
    applicationCommandPatchRequestPartial:
      "ApplicationCommandPatchRequestPartial",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateGuildApplicationCommandRequest$ {
  /** @deprecated use `UpdateGuildApplicationCommandRequest$inboundSchema` instead. */
  export const inboundSchema =
    UpdateGuildApplicationCommandRequest$inboundSchema;
  /** @deprecated use `UpdateGuildApplicationCommandRequest$outboundSchema` instead. */
  export const outboundSchema =
    UpdateGuildApplicationCommandRequest$outboundSchema;
  /** @deprecated use `UpdateGuildApplicationCommandRequest$Outbound` instead. */
  export type Outbound = UpdateGuildApplicationCommandRequest$Outbound;
}
