/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type UpdateGuildTemplateRequestBody = {
  name?: string | undefined;
  description?: string | null | undefined;
};

export type UpdateGuildTemplateRequest = {
  guildId: string;
  code: string;
  requestBody: UpdateGuildTemplateRequestBody;
};

/** @internal */
export const UpdateGuildTemplateRequestBody$inboundSchema: z.ZodType<
  UpdateGuildTemplateRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
  description: z.nullable(z.string()).optional(),
});

/** @internal */
export type UpdateGuildTemplateRequestBody$Outbound = {
  name?: string | undefined;
  description?: string | null | undefined;
};

/** @internal */
export const UpdateGuildTemplateRequestBody$outboundSchema: z.ZodType<
  UpdateGuildTemplateRequestBody$Outbound,
  z.ZodTypeDef,
  UpdateGuildTemplateRequestBody
> = z.object({
  name: z.string().optional(),
  description: z.nullable(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateGuildTemplateRequestBody$ {
  /** @deprecated use `UpdateGuildTemplateRequestBody$inboundSchema` instead. */
  export const inboundSchema = UpdateGuildTemplateRequestBody$inboundSchema;
  /** @deprecated use `UpdateGuildTemplateRequestBody$outboundSchema` instead. */
  export const outboundSchema = UpdateGuildTemplateRequestBody$outboundSchema;
  /** @deprecated use `UpdateGuildTemplateRequestBody$Outbound` instead. */
  export type Outbound = UpdateGuildTemplateRequestBody$Outbound;
}

/** @internal */
export const UpdateGuildTemplateRequest$inboundSchema: z.ZodType<
  UpdateGuildTemplateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  guild_id: z.string(),
  code: z.string(),
  RequestBody: z.lazy(() => UpdateGuildTemplateRequestBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "guild_id": "guildId",
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type UpdateGuildTemplateRequest$Outbound = {
  guild_id: string;
  code: string;
  RequestBody: UpdateGuildTemplateRequestBody$Outbound;
};

/** @internal */
export const UpdateGuildTemplateRequest$outboundSchema: z.ZodType<
  UpdateGuildTemplateRequest$Outbound,
  z.ZodTypeDef,
  UpdateGuildTemplateRequest
> = z.object({
  guildId: z.string(),
  code: z.string(),
  requestBody: z.lazy(() => UpdateGuildTemplateRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    guildId: "guild_id",
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateGuildTemplateRequest$ {
  /** @deprecated use `UpdateGuildTemplateRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateGuildTemplateRequest$inboundSchema;
  /** @deprecated use `UpdateGuildTemplateRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateGuildTemplateRequest$outboundSchema;
  /** @deprecated use `UpdateGuildTemplateRequest$Outbound` instead. */
  export type Outbound = UpdateGuildTemplateRequest$Outbound;
}
