/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type UpdateAutoModerationRuleRequestBody =
  | components.DefaultKeywordListUpsertRequestPartial
  | components.KeywordUpsertRequestPartial
  | components.MLSpamUpsertRequestPartial
  | components.MentionSpamUpsertRequestPartial;

export type UpdateAutoModerationRuleRequest = {
  guildId: string;
  ruleId: string;
  requestBody:
    | components.DefaultKeywordListUpsertRequestPartial
    | components.KeywordUpsertRequestPartial
    | components.MLSpamUpsertRequestPartial
    | components.MentionSpamUpsertRequestPartial;
};

/**
 * 200 response for update_auto_moderation_rule
 */
export type UpdateAutoModerationRuleResponseBody =
  | components.DefaultKeywordRuleResponse
  | components.KeywordRuleResponse
  | components.MLSpamRuleResponse
  | components.MentionSpamRuleResponse
  | components.SpamLinkRuleResponse;

/** @internal */
export const UpdateAutoModerationRuleRequestBody$inboundSchema: z.ZodType<
  UpdateAutoModerationRuleRequestBody,
  z.ZodTypeDef,
  unknown
> = z.union([
  components.DefaultKeywordListUpsertRequestPartial$inboundSchema,
  components.KeywordUpsertRequestPartial$inboundSchema,
  components.MLSpamUpsertRequestPartial$inboundSchema,
  components.MentionSpamUpsertRequestPartial$inboundSchema,
]);

/** @internal */
export type UpdateAutoModerationRuleRequestBody$Outbound =
  | components.DefaultKeywordListUpsertRequestPartial$Outbound
  | components.KeywordUpsertRequestPartial$Outbound
  | components.MLSpamUpsertRequestPartial$Outbound
  | components.MentionSpamUpsertRequestPartial$Outbound;

/** @internal */
export const UpdateAutoModerationRuleRequestBody$outboundSchema: z.ZodType<
  UpdateAutoModerationRuleRequestBody$Outbound,
  z.ZodTypeDef,
  UpdateAutoModerationRuleRequestBody
> = z.union([
  components.DefaultKeywordListUpsertRequestPartial$outboundSchema,
  components.KeywordUpsertRequestPartial$outboundSchema,
  components.MLSpamUpsertRequestPartial$outboundSchema,
  components.MentionSpamUpsertRequestPartial$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateAutoModerationRuleRequestBody$ {
  /** @deprecated use `UpdateAutoModerationRuleRequestBody$inboundSchema` instead. */
  export const inboundSchema =
    UpdateAutoModerationRuleRequestBody$inboundSchema;
  /** @deprecated use `UpdateAutoModerationRuleRequestBody$outboundSchema` instead. */
  export const outboundSchema =
    UpdateAutoModerationRuleRequestBody$outboundSchema;
  /** @deprecated use `UpdateAutoModerationRuleRequestBody$Outbound` instead. */
  export type Outbound = UpdateAutoModerationRuleRequestBody$Outbound;
}

/** @internal */
export const UpdateAutoModerationRuleRequest$inboundSchema: z.ZodType<
  UpdateAutoModerationRuleRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  guild_id: z.string(),
  rule_id: z.string(),
  RequestBody: z.union([
    components.DefaultKeywordListUpsertRequestPartial$inboundSchema,
    components.KeywordUpsertRequestPartial$inboundSchema,
    components.MLSpamUpsertRequestPartial$inboundSchema,
    components.MentionSpamUpsertRequestPartial$inboundSchema,
  ]),
}).transform((v) => {
  return remap$(v, {
    "guild_id": "guildId",
    "rule_id": "ruleId",
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type UpdateAutoModerationRuleRequest$Outbound = {
  guild_id: string;
  rule_id: string;
  RequestBody:
    | components.DefaultKeywordListUpsertRequestPartial$Outbound
    | components.KeywordUpsertRequestPartial$Outbound
    | components.MLSpamUpsertRequestPartial$Outbound
    | components.MentionSpamUpsertRequestPartial$Outbound;
};

/** @internal */
export const UpdateAutoModerationRuleRequest$outboundSchema: z.ZodType<
  UpdateAutoModerationRuleRequest$Outbound,
  z.ZodTypeDef,
  UpdateAutoModerationRuleRequest
> = z.object({
  guildId: z.string(),
  ruleId: z.string(),
  requestBody: z.union([
    components.DefaultKeywordListUpsertRequestPartial$outboundSchema,
    components.KeywordUpsertRequestPartial$outboundSchema,
    components.MLSpamUpsertRequestPartial$outboundSchema,
    components.MentionSpamUpsertRequestPartial$outboundSchema,
  ]),
}).transform((v) => {
  return remap$(v, {
    guildId: "guild_id",
    ruleId: "rule_id",
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateAutoModerationRuleRequest$ {
  /** @deprecated use `UpdateAutoModerationRuleRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateAutoModerationRuleRequest$inboundSchema;
  /** @deprecated use `UpdateAutoModerationRuleRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateAutoModerationRuleRequest$outboundSchema;
  /** @deprecated use `UpdateAutoModerationRuleRequest$Outbound` instead. */
  export type Outbound = UpdateAutoModerationRuleRequest$Outbound;
}

/** @internal */
export const UpdateAutoModerationRuleResponseBody$inboundSchema: z.ZodType<
  UpdateAutoModerationRuleResponseBody,
  z.ZodTypeDef,
  unknown
> = z.union([
  components.DefaultKeywordRuleResponse$inboundSchema,
  components.KeywordRuleResponse$inboundSchema,
  components.MLSpamRuleResponse$inboundSchema,
  components.MentionSpamRuleResponse$inboundSchema,
  components.SpamLinkRuleResponse$inboundSchema,
]);

/** @internal */
export type UpdateAutoModerationRuleResponseBody$Outbound =
  | components.DefaultKeywordRuleResponse$Outbound
  | components.KeywordRuleResponse$Outbound
  | components.MLSpamRuleResponse$Outbound
  | components.MentionSpamRuleResponse$Outbound
  | components.SpamLinkRuleResponse$Outbound;

/** @internal */
export const UpdateAutoModerationRuleResponseBody$outboundSchema: z.ZodType<
  UpdateAutoModerationRuleResponseBody$Outbound,
  z.ZodTypeDef,
  UpdateAutoModerationRuleResponseBody
> = z.union([
  components.DefaultKeywordRuleResponse$outboundSchema,
  components.KeywordRuleResponse$outboundSchema,
  components.MLSpamRuleResponse$outboundSchema,
  components.MentionSpamRuleResponse$outboundSchema,
  components.SpamLinkRuleResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateAutoModerationRuleResponseBody$ {
  /** @deprecated use `UpdateAutoModerationRuleResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    UpdateAutoModerationRuleResponseBody$inboundSchema;
  /** @deprecated use `UpdateAutoModerationRuleResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    UpdateAutoModerationRuleResponseBody$outboundSchema;
  /** @deprecated use `UpdateAutoModerationRuleResponseBody$Outbound` instead. */
  export type Outbound = UpdateAutoModerationRuleResponseBody$Outbound;
}
