/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type UpdateGuildEmojiRequestBody = {
  name?: string | undefined;
  roles?: Array<string> | null | undefined;
};

export type UpdateGuildEmojiRequest = {
  guildId: string;
  emojiId: string;
  requestBody: UpdateGuildEmojiRequestBody;
};

/** @internal */
export const UpdateGuildEmojiRequestBody$inboundSchema: z.ZodType<
  UpdateGuildEmojiRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
  roles: z.nullable(z.array(z.string())).optional(),
});

/** @internal */
export type UpdateGuildEmojiRequestBody$Outbound = {
  name?: string | undefined;
  roles?: Array<string> | null | undefined;
};

/** @internal */
export const UpdateGuildEmojiRequestBody$outboundSchema: z.ZodType<
  UpdateGuildEmojiRequestBody$Outbound,
  z.ZodTypeDef,
  UpdateGuildEmojiRequestBody
> = z.object({
  name: z.string().optional(),
  roles: z.nullable(z.array(z.string())).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateGuildEmojiRequestBody$ {
  /** @deprecated use `UpdateGuildEmojiRequestBody$inboundSchema` instead. */
  export const inboundSchema = UpdateGuildEmojiRequestBody$inboundSchema;
  /** @deprecated use `UpdateGuildEmojiRequestBody$outboundSchema` instead. */
  export const outboundSchema = UpdateGuildEmojiRequestBody$outboundSchema;
  /** @deprecated use `UpdateGuildEmojiRequestBody$Outbound` instead. */
  export type Outbound = UpdateGuildEmojiRequestBody$Outbound;
}

/** @internal */
export const UpdateGuildEmojiRequest$inboundSchema: z.ZodType<
  UpdateGuildEmojiRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  guild_id: z.string(),
  emoji_id: z.string(),
  RequestBody: z.lazy(() => UpdateGuildEmojiRequestBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "guild_id": "guildId",
    "emoji_id": "emojiId",
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type UpdateGuildEmojiRequest$Outbound = {
  guild_id: string;
  emoji_id: string;
  RequestBody: UpdateGuildEmojiRequestBody$Outbound;
};

/** @internal */
export const UpdateGuildEmojiRequest$outboundSchema: z.ZodType<
  UpdateGuildEmojiRequest$Outbound,
  z.ZodTypeDef,
  UpdateGuildEmojiRequest
> = z.object({
  guildId: z.string(),
  emojiId: z.string(),
  requestBody: z.lazy(() => UpdateGuildEmojiRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    guildId: "guild_id",
    emojiId: "emoji_id",
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateGuildEmojiRequest$ {
  /** @deprecated use `UpdateGuildEmojiRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateGuildEmojiRequest$inboundSchema;
  /** @deprecated use `UpdateGuildEmojiRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateGuildEmojiRequest$outboundSchema;
  /** @deprecated use `UpdateGuildEmojiRequest$Outbound` instead. */
  export type Outbound = UpdateGuildEmojiRequest$Outbound;
}
