/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ApplicationCommandOptionNumberChoice = {
  name: string;
  nameLocalizations?: { [k: string]: string } | null | undefined;
  value: number;
};

/** @internal */
export const ApplicationCommandOptionNumberChoice$inboundSchema: z.ZodType<
  ApplicationCommandOptionNumberChoice,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  name_localizations: z.nullable(z.record(z.string())).optional(),
  value: z.number(),
}).transform((v) => {
  return remap$(v, {
    "name_localizations": "nameLocalizations",
  });
});

/** @internal */
export type ApplicationCommandOptionNumberChoice$Outbound = {
  name: string;
  name_localizations?: { [k: string]: string } | null | undefined;
  value: number;
};

/** @internal */
export const ApplicationCommandOptionNumberChoice$outboundSchema: z.ZodType<
  ApplicationCommandOptionNumberChoice$Outbound,
  z.ZodTypeDef,
  ApplicationCommandOptionNumberChoice
> = z.object({
  name: z.string(),
  nameLocalizations: z.nullable(z.record(z.string())).optional(),
  value: z.number(),
}).transform((v) => {
  return remap$(v, {
    nameLocalizations: "name_localizations",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApplicationCommandOptionNumberChoice$ {
  /** @deprecated use `ApplicationCommandOptionNumberChoice$inboundSchema` instead. */
  export const inboundSchema =
    ApplicationCommandOptionNumberChoice$inboundSchema;
  /** @deprecated use `ApplicationCommandOptionNumberChoice$outboundSchema` instead. */
  export const outboundSchema =
    ApplicationCommandOptionNumberChoice$outboundSchema;
  /** @deprecated use `ApplicationCommandOptionNumberChoice$Outbound` instead. */
  export type Outbound = ApplicationCommandOptionNumberChoice$Outbound;
}

export function applicationCommandOptionNumberChoiceToJSON(
  applicationCommandOptionNumberChoice: ApplicationCommandOptionNumberChoice,
): string {
  return JSON.stringify(
    ApplicationCommandOptionNumberChoice$outboundSchema.parse(
      applicationCommandOptionNumberChoice,
    ),
  );
}

export function applicationCommandOptionNumberChoiceFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationCommandOptionNumberChoice, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ApplicationCommandOptionNumberChoice$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationCommandOptionNumberChoice' from JSON`,
  );
}
