/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  BlockMessageActionMetadataResponse,
  BlockMessageActionMetadataResponse$inboundSchema,
  BlockMessageActionMetadataResponse$Outbound,
  BlockMessageActionMetadataResponse$outboundSchema,
} from "./blockmessageactionmetadataresponse.js";

export type BlockMessageActionResponse = {
  type?: 1 | undefined;
  metadata: BlockMessageActionMetadataResponse;
};

/** @internal */
export const BlockMessageActionResponse$inboundSchema: z.ZodType<
  BlockMessageActionResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal(1).optional(),
  metadata: BlockMessageActionMetadataResponse$inboundSchema,
});

/** @internal */
export type BlockMessageActionResponse$Outbound = {
  type: 1;
  metadata: BlockMessageActionMetadataResponse$Outbound;
};

/** @internal */
export const BlockMessageActionResponse$outboundSchema: z.ZodType<
  BlockMessageActionResponse$Outbound,
  z.ZodTypeDef,
  BlockMessageActionResponse
> = z.object({
  type: z.literal(1).default(1 as const),
  metadata: BlockMessageActionMetadataResponse$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BlockMessageActionResponse$ {
  /** @deprecated use `BlockMessageActionResponse$inboundSchema` instead. */
  export const inboundSchema = BlockMessageActionResponse$inboundSchema;
  /** @deprecated use `BlockMessageActionResponse$outboundSchema` instead. */
  export const outboundSchema = BlockMessageActionResponse$outboundSchema;
  /** @deprecated use `BlockMessageActionResponse$Outbound` instead. */
  export type Outbound = BlockMessageActionResponse$Outbound;
}
