/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ConnectedAccountGuildResponse = {
  id: string;
  name: string;
  icon?: string | null | undefined;
};

/** @internal */
export const ConnectedAccountGuildResponse$inboundSchema: z.ZodType<
  ConnectedAccountGuildResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  name: z.string(),
  icon: z.nullable(z.string()).optional(),
});

/** @internal */
export type ConnectedAccountGuildResponse$Outbound = {
  id: string;
  name: string;
  icon?: string | null | undefined;
};

/** @internal */
export const ConnectedAccountGuildResponse$outboundSchema: z.ZodType<
  ConnectedAccountGuildResponse$Outbound,
  z.ZodTypeDef,
  ConnectedAccountGuildResponse
> = z.object({
  id: z.string(),
  name: z.string(),
  icon: z.nullable(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConnectedAccountGuildResponse$ {
  /** @deprecated use `ConnectedAccountGuildResponse$inboundSchema` instead. */
  export const inboundSchema = ConnectedAccountGuildResponse$inboundSchema;
  /** @deprecated use `ConnectedAccountGuildResponse$outboundSchema` instead. */
  export const outboundSchema = ConnectedAccountGuildResponse$outboundSchema;
  /** @deprecated use `ConnectedAccountGuildResponse$Outbound` instead. */
  export type Outbound = ConnectedAccountGuildResponse$Outbound;
}
