/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type DefaultKeywordListTriggerMetadata = {
  allowList?: Array<string> | null | undefined;
  presets?: Array<number> | null | undefined;
};

/** @internal */
export const DefaultKeywordListTriggerMetadata$inboundSchema: z.ZodType<
  DefaultKeywordListTriggerMetadata,
  z.ZodTypeDef,
  unknown
> = z.object({
  allow_list: z.nullable(z.array(z.string())).optional(),
  presets: z.nullable(z.array(z.number().int())).optional(),
}).transform((v) => {
  return remap$(v, {
    "allow_list": "allowList",
  });
});

/** @internal */
export type DefaultKeywordListTriggerMetadata$Outbound = {
  allow_list?: Array<string> | null | undefined;
  presets?: Array<number> | null | undefined;
};

/** @internal */
export const DefaultKeywordListTriggerMetadata$outboundSchema: z.ZodType<
  DefaultKeywordListTriggerMetadata$Outbound,
  z.ZodTypeDef,
  DefaultKeywordListTriggerMetadata
> = z.object({
  allowList: z.nullable(z.array(z.string())).optional(),
  presets: z.nullable(z.array(z.number().int())).optional(),
}).transform((v) => {
  return remap$(v, {
    allowList: "allow_list",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DefaultKeywordListTriggerMetadata$ {
  /** @deprecated use `DefaultKeywordListTriggerMetadata$inboundSchema` instead. */
  export const inboundSchema = DefaultKeywordListTriggerMetadata$inboundSchema;
  /** @deprecated use `DefaultKeywordListTriggerMetadata$outboundSchema` instead. */
  export const outboundSchema =
    DefaultKeywordListTriggerMetadata$outboundSchema;
  /** @deprecated use `DefaultKeywordListTriggerMetadata$Outbound` instead. */
  export type Outbound = DefaultKeywordListTriggerMetadata$Outbound;
}
