/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type EntityMetadataStageInstanceResponse = {};

/** @internal */
export const EntityMetadataStageInstanceResponse$inboundSchema: z.ZodType<
  EntityMetadataStageInstanceResponse,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type EntityMetadataStageInstanceResponse$Outbound = {};

/** @internal */
export const EntityMetadataStageInstanceResponse$outboundSchema: z.ZodType<
  EntityMetadataStageInstanceResponse$Outbound,
  z.ZodTypeDef,
  EntityMetadataStageInstanceResponse
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EntityMetadataStageInstanceResponse$ {
  /** @deprecated use `EntityMetadataStageInstanceResponse$inboundSchema` instead. */
  export const inboundSchema =
    EntityMetadataStageInstanceResponse$inboundSchema;
  /** @deprecated use `EntityMetadataStageInstanceResponse$outboundSchema` instead. */
  export const outboundSchema =
    EntityMetadataStageInstanceResponse$outboundSchema;
  /** @deprecated use `EntityMetadataStageInstanceResponse$Outbound` instead. */
  export type Outbound = EntityMetadataStageInstanceResponse$Outbound;
}

export function entityMetadataStageInstanceResponseToJSON(
  entityMetadataStageInstanceResponse: EntityMetadataStageInstanceResponse,
): string {
  return JSON.stringify(
    EntityMetadataStageInstanceResponse$outboundSchema.parse(
      entityMetadataStageInstanceResponse,
    ),
  );
}

export function entityMetadataStageInstanceResponseFromJSON(
  jsonString: string,
): SafeParseResult<EntityMetadataStageInstanceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      EntityMetadataStageInstanceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EntityMetadataStageInstanceResponse' from JSON`,
  );
}
