/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type GuildTemplateRoleResponse = {
  id: number;
  name: string;
  permissions: string;
  color: number;
  hoist: boolean;
  mentionable: boolean;
  icon?: string | null | undefined;
  unicodeEmoji?: string | null | undefined;
};

/** @internal */
export const GuildTemplateRoleResponse$inboundSchema: z.ZodType<
  GuildTemplateRoleResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
  name: z.string(),
  permissions: z.string(),
  color: z.number().int(),
  hoist: z.boolean(),
  mentionable: z.boolean(),
  icon: z.nullable(z.string()).optional(),
  unicode_emoji: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "unicode_emoji": "unicodeEmoji",
  });
});

/** @internal */
export type GuildTemplateRoleResponse$Outbound = {
  id: number;
  name: string;
  permissions: string;
  color: number;
  hoist: boolean;
  mentionable: boolean;
  icon?: string | null | undefined;
  unicode_emoji?: string | null | undefined;
};

/** @internal */
export const GuildTemplateRoleResponse$outboundSchema: z.ZodType<
  GuildTemplateRoleResponse$Outbound,
  z.ZodTypeDef,
  GuildTemplateRoleResponse
> = z.object({
  id: z.number().int(),
  name: z.string(),
  permissions: z.string(),
  color: z.number().int(),
  hoist: z.boolean(),
  mentionable: z.boolean(),
  icon: z.nullable(z.string()).optional(),
  unicodeEmoji: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    unicodeEmoji: "unicode_emoji",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GuildTemplateRoleResponse$ {
  /** @deprecated use `GuildTemplateRoleResponse$inboundSchema` instead. */
  export const inboundSchema = GuildTemplateRoleResponse$inboundSchema;
  /** @deprecated use `GuildTemplateRoleResponse$outboundSchema` instead. */
  export const outboundSchema = GuildTemplateRoleResponse$outboundSchema;
  /** @deprecated use `GuildTemplateRoleResponse$Outbound` instead. */
  export type Outbound = GuildTemplateRoleResponse$Outbound;
}
