/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type GuildWelcomeChannel = {
  channelId: string;
  description: string;
  emojiId?: string | null | undefined;
  emojiName?: string | null | undefined;
};

/** @internal */
export const GuildWelcomeChannel$inboundSchema: z.ZodType<
  GuildWelcomeChannel,
  z.ZodTypeDef,
  unknown
> = z.object({
  channel_id: z.string(),
  description: z.string(),
  emoji_id: z.nullable(z.string()).optional(),
  emoji_name: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "channel_id": "channelId",
    "emoji_id": "emojiId",
    "emoji_name": "emojiName",
  });
});

/** @internal */
export type GuildWelcomeChannel$Outbound = {
  channel_id: string;
  description: string;
  emoji_id?: string | null | undefined;
  emoji_name?: string | null | undefined;
};

/** @internal */
export const GuildWelcomeChannel$outboundSchema: z.ZodType<
  GuildWelcomeChannel$Outbound,
  z.ZodTypeDef,
  GuildWelcomeChannel
> = z.object({
  channelId: z.string(),
  description: z.string(),
  emojiId: z.nullable(z.string()).optional(),
  emojiName: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    channelId: "channel_id",
    emojiId: "emoji_id",
    emojiName: "emoji_name",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GuildWelcomeChannel$ {
  /** @deprecated use `GuildWelcomeChannel$inboundSchema` instead. */
  export const inboundSchema = GuildWelcomeChannel$inboundSchema;
  /** @deprecated use `GuildWelcomeChannel$outboundSchema` instead. */
  export const outboundSchema = GuildWelcomeChannel$outboundSchema;
  /** @deprecated use `GuildWelcomeChannel$Outbound` instead. */
  export type Outbound = GuildWelcomeChannel$Outbound;
}
