/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  GuildWelcomeScreenChannelResponse,
  GuildWelcomeScreenChannelResponse$inboundSchema,
  GuildWelcomeScreenChannelResponse$Outbound,
  GuildWelcomeScreenChannelResponse$outboundSchema,
} from "./guildwelcomescreenchannelresponse.js";

export type GuildWelcomeScreenResponse = {
  description?: string | null | undefined;
  welcomeChannels: Array<GuildWelcomeScreenChannelResponse>;
};

/** @internal */
export const GuildWelcomeScreenResponse$inboundSchema: z.ZodType<
  GuildWelcomeScreenResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  description: z.nullable(z.string()).optional(),
  welcome_channels: z.array(GuildWelcomeScreenChannelResponse$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "welcome_channels": "welcomeChannels",
  });
});

/** @internal */
export type GuildWelcomeScreenResponse$Outbound = {
  description?: string | null | undefined;
  welcome_channels: Array<GuildWelcomeScreenChannelResponse$Outbound>;
};

/** @internal */
export const GuildWelcomeScreenResponse$outboundSchema: z.ZodType<
  GuildWelcomeScreenResponse$Outbound,
  z.ZodTypeDef,
  GuildWelcomeScreenResponse
> = z.object({
  description: z.nullable(z.string()).optional(),
  welcomeChannels: z.array(GuildWelcomeScreenChannelResponse$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    welcomeChannels: "welcome_channels",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GuildWelcomeScreenResponse$ {
  /** @deprecated use `GuildWelcomeScreenResponse$inboundSchema` instead. */
  export const inboundSchema = GuildWelcomeScreenResponse$inboundSchema;
  /** @deprecated use `GuildWelcomeScreenResponse$outboundSchema` instead. */
  export const outboundSchema = GuildWelcomeScreenResponse$outboundSchema;
  /** @deprecated use `GuildWelcomeScreenResponse$Outbound` instead. */
  export type Outbound = GuildWelcomeScreenResponse$Outbound;
}

export function guildWelcomeScreenResponseToJSON(
  guildWelcomeScreenResponse: GuildWelcomeScreenResponse,
): string {
  return JSON.stringify(
    GuildWelcomeScreenResponse$outboundSchema.parse(guildWelcomeScreenResponse),
  );
}

export function guildWelcomeScreenResponseFromJSON(
  jsonString: string,
): SafeParseResult<GuildWelcomeScreenResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GuildWelcomeScreenResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GuildWelcomeScreenResponse' from JSON`,
  );
}
