/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type GuildPruneResponse = {
  pruned?: number | null | undefined;
};

/** @internal */
export const GuildPruneResponse$inboundSchema: z.ZodType<
  GuildPruneResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  pruned: z.nullable(z.number().int()).optional(),
});

/** @internal */
export type GuildPruneResponse$Outbound = {
  pruned?: number | null | undefined;
};

/** @internal */
export const GuildPruneResponse$outboundSchema: z.ZodType<
  GuildPruneResponse$Outbound,
  z.ZodTypeDef,
  GuildPruneResponse
> = z.object({
  pruned: z.nullable(z.number().int()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GuildPruneResponse$ {
  /** @deprecated use `GuildPruneResponse$inboundSchema` instead. */
  export const inboundSchema = GuildPruneResponse$inboundSchema;
  /** @deprecated use `GuildPruneResponse$outboundSchema` instead. */
  export const outboundSchema = GuildPruneResponse$outboundSchema;
  /** @deprecated use `GuildPruneResponse$Outbound` instead. */
  export type Outbound = GuildPruneResponse$Outbound;
}
