/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type GuildTemplateChannelTags = {
  name: string;
  emojiId?: string | null | undefined;
  emojiName?: string | null | undefined;
  moderated?: boolean | null | undefined;
};

/** @internal */
export const GuildTemplateChannelTags$inboundSchema: z.ZodType<
  GuildTemplateChannelTags,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  emoji_id: z.nullable(z.string()).optional(),
  emoji_name: z.nullable(z.string()).optional(),
  moderated: z.nullable(z.boolean()).optional(),
}).transform((v) => {
  return remap$(v, {
    "emoji_id": "emojiId",
    "emoji_name": "emojiName",
  });
});

/** @internal */
export type GuildTemplateChannelTags$Outbound = {
  name: string;
  emoji_id?: string | null | undefined;
  emoji_name?: string | null | undefined;
  moderated?: boolean | null | undefined;
};

/** @internal */
export const GuildTemplateChannelTags$outboundSchema: z.ZodType<
  GuildTemplateChannelTags$Outbound,
  z.ZodTypeDef,
  GuildTemplateChannelTags
> = z.object({
  name: z.string(),
  emojiId: z.nullable(z.string()).optional(),
  emojiName: z.nullable(z.string()).optional(),
  moderated: z.nullable(z.boolean()).optional(),
}).transform((v) => {
  return remap$(v, {
    emojiId: "emoji_id",
    emojiName: "emoji_name",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GuildTemplateChannelTags$ {
  /** @deprecated use `GuildTemplateChannelTags$inboundSchema` instead. */
  export const inboundSchema = GuildTemplateChannelTags$inboundSchema;
  /** @deprecated use `GuildTemplateChannelTags$outboundSchema` instead. */
  export const outboundSchema = GuildTemplateChannelTags$outboundSchema;
  /** @deprecated use `GuildTemplateChannelTags$Outbound` instead. */
  export type Outbound = GuildTemplateChannelTags$Outbound;
}
