/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type KeywordTriggerMetadata = {
  keywordFilter?: Array<string> | null | undefined;
  regexPatterns?: Array<string> | null | undefined;
  allowList?: Array<string> | null | undefined;
};

/** @internal */
export const KeywordTriggerMetadata$inboundSchema: z.ZodType<
  KeywordTriggerMetadata,
  z.ZodTypeDef,
  unknown
> = z.object({
  keyword_filter: z.nullable(z.array(z.string())).optional(),
  regex_patterns: z.nullable(z.array(z.string())).optional(),
  allow_list: z.nullable(z.array(z.string())).optional(),
}).transform((v) => {
  return remap$(v, {
    "keyword_filter": "keywordFilter",
    "regex_patterns": "regexPatterns",
    "allow_list": "allowList",
  });
});

/** @internal */
export type KeywordTriggerMetadata$Outbound = {
  keyword_filter?: Array<string> | null | undefined;
  regex_patterns?: Array<string> | null | undefined;
  allow_list?: Array<string> | null | undefined;
};

/** @internal */
export const KeywordTriggerMetadata$outboundSchema: z.ZodType<
  KeywordTriggerMetadata$Outbound,
  z.ZodTypeDef,
  KeywordTriggerMetadata
> = z.object({
  keywordFilter: z.nullable(z.array(z.string())).optional(),
  regexPatterns: z.nullable(z.array(z.string())).optional(),
  allowList: z.nullable(z.array(z.string())).optional(),
}).transform((v) => {
  return remap$(v, {
    keywordFilter: "keyword_filter",
    regexPatterns: "regex_patterns",
    allowList: "allow_list",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace KeywordTriggerMetadata$ {
  /** @deprecated use `KeywordTriggerMetadata$inboundSchema` instead. */
  export const inboundSchema = KeywordTriggerMetadata$inboundSchema;
  /** @deprecated use `KeywordTriggerMetadata$outboundSchema` instead. */
  export const outboundSchema = KeywordTriggerMetadata$outboundSchema;
  /** @deprecated use `KeywordTriggerMetadata$Outbound` instead. */
  export type Outbound = KeywordTriggerMetadata$Outbound;
}
