/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  SoundboardSoundResponse,
  SoundboardSoundResponse$inboundSchema,
  SoundboardSoundResponse$Outbound,
  SoundboardSoundResponse$outboundSchema,
} from "./soundboardsoundresponse.js";

export type ListGuildSoundboardSoundsResponse = {
  items: Array<SoundboardSoundResponse>;
};

/** @internal */
export const ListGuildSoundboardSoundsResponse$inboundSchema: z.ZodType<
  ListGuildSoundboardSoundsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(SoundboardSoundResponse$inboundSchema),
});

/** @internal */
export type ListGuildSoundboardSoundsResponse$Outbound = {
  items: Array<SoundboardSoundResponse$Outbound>;
};

/** @internal */
export const ListGuildSoundboardSoundsResponse$outboundSchema: z.ZodType<
  ListGuildSoundboardSoundsResponse$Outbound,
  z.ZodTypeDef,
  ListGuildSoundboardSoundsResponse
> = z.object({
  items: z.array(SoundboardSoundResponse$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListGuildSoundboardSoundsResponse$ {
  /** @deprecated use `ListGuildSoundboardSoundsResponse$inboundSchema` instead. */
  export const inboundSchema = ListGuildSoundboardSoundsResponse$inboundSchema;
  /** @deprecated use `ListGuildSoundboardSoundsResponse$outboundSchema` instead. */
  export const outboundSchema =
    ListGuildSoundboardSoundsResponse$outboundSchema;
  /** @deprecated use `ListGuildSoundboardSoundsResponse$Outbound` instead. */
  export type Outbound = ListGuildSoundboardSoundsResponse$Outbound;
}
