/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  PollEmoji,
  PollEmoji$inboundSchema,
  PollEmoji$Outbound,
  PollEmoji$outboundSchema,
} from "./pollemoji.js";

export type PollMedia = {
  text?: string | null | undefined;
  emoji?: PollEmoji | null | undefined;
};

/** @internal */
export const PollMedia$inboundSchema: z.ZodType<
  PollMedia,
  z.ZodTypeDef,
  unknown
> = z.object({
  text: z.nullable(z.string()).optional(),
  emoji: z.nullable(PollEmoji$inboundSchema).optional(),
});

/** @internal */
export type PollMedia$Outbound = {
  text?: string | null | undefined;
  emoji?: PollEmoji$Outbound | null | undefined;
};

/** @internal */
export const PollMedia$outboundSchema: z.ZodType<
  PollMedia$Outbound,
  z.ZodTypeDef,
  PollMedia
> = z.object({
  text: z.nullable(z.string()).optional(),
  emoji: z.nullable(PollEmoji$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PollMedia$ {
  /** @deprecated use `PollMedia$inboundSchema` instead. */
  export const inboundSchema = PollMedia$inboundSchema;
  /** @deprecated use `PollMedia$outboundSchema` instead. */
  export const outboundSchema = PollMedia$outboundSchema;
  /** @deprecated use `PollMedia$Outbound` instead. */
  export type Outbound = PollMedia$Outbound;
}

export function pollMediaToJSON(pollMedia: PollMedia): string {
  return JSON.stringify(PollMedia$outboundSchema.parse(pollMedia));
}

export function pollMediaFromJSON(
  jsonString: string,
): SafeParseResult<PollMedia, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PollMedia$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PollMedia' from JSON`,
  );
}
