/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type WidgetActivity = {
  name: string;
};

/** @internal */
export const WidgetActivity$inboundSchema: z.ZodType<
  WidgetActivity,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
});

/** @internal */
export type WidgetActivity$Outbound = {
  name: string;
};

/** @internal */
export const WidgetActivity$outboundSchema: z.ZodType<
  WidgetActivity$Outbound,
  z.ZodTypeDef,
  WidgetActivity
> = z.object({
  name: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WidgetActivity$ {
  /** @deprecated use `WidgetActivity$inboundSchema` instead. */
  export const inboundSchema = WidgetActivity$inboundSchema;
  /** @deprecated use `WidgetActivity$outboundSchema` instead. */
  export const outboundSchema = WidgetActivity$outboundSchema;
  /** @deprecated use `WidgetActivity$Outbound` instead. */
  export type Outbound = WidgetActivity$Outbound;
}
